[tool.poetry]
name = "openbb-binance"
version = "1.2.1"
description = ""
authors = ["OpenBB Team <hello@openbb.co>"]
license = "AGPL-3.0-only"
readme = "README.md"
packages = [{ include = "openbb_binance" }]

[tool.poetry.dependencies]
python = "^3.8"
openbb-core = "^1.2.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
binance = "openbb_binance:binance_provider"
